---
# tasks file for ansible-apt

- name: Run the equivalent of "apt-get update" as a separate step
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 1800

- name: Upgrade all packages to the latest version
  become: yes 
  apt:
    name: "*"
    state: latest

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes 
  apt:
    autoremove: yes

- name: "Install packages defined in apt_packages"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_packages }}"
  when: apt_packages|default([])|count > 0